# /etc/strongswan/ipsec.conf
# Túnel VPN IPSec — EC2 WEFLY ↔ BFC

config setup
    charondebug="ike 2, knl 2, cfg 2"

conn bfc-tunnel
    type=tunnel
    auto=start
    keyexchange=ikev2

    # === LADO WEFLY (EC2) ===
    left=%defaultroute
    leftid=__ELASTIC_IP__
    leftsubnet=__IP_PRIVADA_EC2__/32

    # === LADO BFC ===
    right=__IP_PUBLICA_BFC__
    rightsubnet=__SUBRED_BFC__

    # === AUTENTICACIÓN ===
    authby=secret
    ike=aes256-sha256-modp2048
    esp=aes256-sha256-modp2048
    ikelifetime=8h
    lifetime=1h
    dpdaction=restart
    dpddelay=30s
    dpdtimeout=120s
